modify bash

diff --git a/.github/workflows/quality-check.yml b/.github/workflows/quality-check.yml
--- a/.github/workflows/quality-check.yml
+++ b/.github/workflows/quality-check.yml
@@ -46,55 +46,60 @@ jobs:
 
       - name: Check Markdown File Headers
         run: |
-          function check_markdown_header {
-              local file=$1
-              local missing_component=false
-
-              local components=(
-                  "^---$"
-                  "^title:.*"
-                  "^published:.*"
-                  "^description:.*"
-                  "^tags:.*"
-                  "^cover_image:.*"
-                  "^canonical_url:.*"
-                  "^id:.*"
-                  "^---$"
-              )
-
-              echo "Checking file: $file"
-              for component in "${components[@]}"; do
-                  if ! grep -Pq "$component" "$file"; then
-                      echo "[❌] $file - Missing header component: $component"
-                      missing_component=true
-                  fi
-              done
-
-              if [ "$missing_component" = true ]; then
-                  return 1
-              else
-                  echo "[✔] $file - All header components present"
-                  return 0
-              fi
-          }
-
-          IFS=$'\n'
-          error=0
-          total_files=0
-          ls -la
-          # Loop over all Markdown files in the current directory
-          for file in *.md; do
-              check_markdown_header "$file" || error=$((error+1))
-              total_files=$((total_files+1))
-          done
-
-          echo "$total_files file(s) checked."
-          if [ $error -ne 0 ]; then
-              echo "There are files without the required header format."
-              exit 1
-          else
-              echo "All Markdown files have the required header format."
-          fi
+            # Define the function to check markdown header
+            function check_markdown_header {
+                local file=$1
+                local missing_component=false
+  
+                local components=(
+                    "^---$"
+                    "^title:.*"
+                    "^published:.*"
+                    "^description:.*"
+                    "^tags:.*"
+                    "^cover_image:.*"
+                    "^canonical_url:.*"
+                    "^id:.*"
+                    "^---$"
+                )
+  
+                echo "Checking file: $file"
+                for component in "${components[@]}"; do
+                    if ! grep -Pq "$component" "$file"; then
+                        echo "[❌] $file - Missing header component: $component"
+                        missing_component=true
+                    fi
+                done
+  
+                if [ "$missing_component" = true ]; then
+                    return 1
+                else
+                    echo "[✔] $file - All header components present"
+                    return 0
+                fi
+            }
+  
+            # Setting up variables and printing all files
+            IFS=$'\n'
+            error=0
+            total_files=0
+            echo "Listing all the files:"
+            ls -la
+  
+            # Loop over all Markdown files in the current directory
+            for file in *.md; do
+                check_markdown_header "$file" || error=$((error+1))
+                total_files=$((total_files+1))
+            done
+  
+            # Output the results
+            echo "$total_files file(s) checked."
+            if [ $error -ne 0 ]; then
+                echo "There are files without the required header format."
+                exit 1
+            else
+                echo "All Markdown files have the required header format."
+            fi
         shell: bash
 
 #   spell-check:
