added simpler check for header

diff --git a/.github/workflows/quality-check.yml b/.github/workflows/quality-check.yml
--- a/.github/workflows/quality-check.yml
+++ b/.github/workflows/quality-check.yml
@@ -36,63 +36,60 @@ jobs:
 
   markdown-header-check:
     runs-on: ubuntu-latest
-
     steps:
-      - uses: actions/checkout@v4
+      - name: Checkout repository
+        uses: actions/checkout@v4
 
       - name: Check Markdown File Headers
-        working-directory: '_posts/'
         run: |
-            # Define function to check headers
-            function check_markdown_header {
-                local file=$1
-                local missing_component=false
+          function check_markdown_header {
+              local file=$1
+              local missing_component=false
 
-                # Header components to check
-                local components=(
-                "^---$"
-                "^title: .+"
-                "^published: .+"
-                "^description: .+"
-                "^tags: .+"
-                "^cover_image: .+"
-                "^canonical_url: .+"
-                "^id: .*"
-                "^---$"
-                )
+              local components=(
+                  "^---$"
+                  "^title:.*"
+                  "^published:.*"
+                  "^description:.*"
+                  "^tags:.*"
+                  "^cover_image:.*"
+                  "^canonical_url:.*"
+                  "^id:.*"
+                  "^---$"
+              )
 
-                for component in "${components[@]}"; do
-                if ! grep -Pq "$component" "$file"; then
-                    echo "Missing or incorrect in \"$file\": $component"
-                    missing_component=true
-                fi
-                done
+              for component in "${components[@]}"; do
+                  if ! grep -Pq "$component" "$file"; then
+                      echo "[❌] $file - Missing header: $component"
+                      missing_component=true
+                  fi
+              done
 
-                if [ "$missing_component" = true ]; then
-                return 1
-                else
-                return 0
-                fi
-            }
+              if [ "$missing_component" = true ]; then
+                  return 1
+              else
+                  echo "[✔] $file"
+                  return 0
+              fi
+          }
 
-            # Change the Internal Field Separator to newline
-            IFS=$'\n'
+          IFS=$'\n'
+          error=0
+          total_files=0
 
-            # Variable to track errors
-            error=0
+          for file in $(git diff --name-only --diff-filter=ACMRT ${{ github.event.before }} ${{ github.sha }} | grep '\.md$'); do
+              check_markdown_header "$file" || error=$((error+1))
+              total_files=$((total_files+1))
+          done
 
-            # Loop through all markdown files in the PR
-            for file in $(git diff --name-only --diff-filter=ACMRT ${{ github.event.before }} ${{ github.sha }} | grep '\.md$'); do
-                check_markdown_header "$file" || error=$((error+1))
-            done
-            
-            # Fail the job if any errors were found
-            if [ $error -ne 0 ]; then
-                echo "There are $error files without the required header format."
-                exit 1
-            else
-                echo "All Markdown files have the required header format."
-            fi
+          echo "$total_files file(s) checked."
+          if [ $error -ne 0 ]; then
+              echo "There are files without the required header format."
+              exit 1
+          else
+              echo "All Markdown files have the required header format."
+          fi
+        shell: bash
 
 #   spell-check:
 #     runs-on: ubuntu-latest
